workflows:
  ios-build:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa

triggers:
  - event: push
    branch: main   # use your actual default branch name
