// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGq6d2wA-TlcOPgffgUOwYx0eQ8cOCHw',
    appId: '1:943121387776:web:c62cbd35f741bee6b0e3e5',
    messagingSenderId: '943121387776',
    projectId: 'laitalianu-128f16a6',
    authDomain: 'laitalianu-128f16a6.firebaseapp.com',
    storageBucket: 'laitalianu-128f16a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMNK-uwHLWs830RAckH0pzN9hGHn2Anc',
    appId: '1:943121387776:android:010d3da5fe77dca9b0e3e5',
    messagingSenderId: '943121387776',
    projectId: 'laitalianu-128f16a6',
    storageBucket: 'laitalianu-128f16a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUbLdQBA2suO3Khqwgi5JEwFqSDk1Ra4',
    appId: '1:943121387776:ios:3d833260120a2bbdb0e3e5',
    messagingSenderId: '943121387776',
    projectId: 'laitalianu-128f16a6',
    storageBucket: 'laitalianu-128f16a6.firebasestorage.app',
    iosBundleId: 'com.example.laItalianu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARUbLdQBA2suO3Khqwgi5JEwFqSDk1Ra4',
    appId: '1:943121387776:ios:3d833260120a2bbdb0e3e5',
    messagingSenderId: '943121387776',
    projectId: 'laitalianu-128f16a6',
    storageBucket: 'laitalianu-128f16a6.firebasestorage.app',
    iosBundleId: 'com.example.laItalianu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFGq6d2wA-TlcOPgffgUOwYx0eQ8cOCHw',
    appId: '1:943121387776:web:3f0d5980f1ea0234b0e3e5',
    messagingSenderId: '943121387776',
    projectId: 'laitalianu-128f16a6',
    authDomain: 'laitalianu-128f16a6.firebaseapp.com',
    storageBucket: 'laitalianu-128f16a6.firebasestorage.app',
  );

}